config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  mount ActionCable.server => "/cable"

  devise_for :users, controllers: {
    registrations: "registrations",
    omniauth_callbacks: "omniauth_callbacks"
  }
  root "pages#index"
  get "/pages/:page", to: "pages#show"

  resources :users do
    resources :list_books, only: :index
    resources :requests, except: [:show, :edit, :update]
  end
  resources :follows, only: [:create, :destroy]
  resources :activities
  resources :categories, only: [:show, :index]
  resources :books, only: [:show, :index] do
    resources :reviews
  end
  resources :reviews, only: :show do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:new, :create, :destroy, :edit, :update]
  end
  resources :marks, only: :update
  resources :favorite_authors, only: [:create, :destroy]
  resources :feed_backs, only: [:new, :create]
  resources :authors, only: [:index, :show]

  namespace :admin do
    root to: "books#index", as: :root
    resources :categories
    resources :books
    resources :users, only: [:index, :show, :destroy]
    resources :requests, only: [:index, :update]
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category

  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors, foreign_key: :book_id
  has_many :reviews, dependent: :destroy
  has_many :marks, dependent: :destroy
  has_many :activities, as: :trackable, class_name: "PublicActivity::Activity",
    foreign_key: "trackable_id", dependent: :destroy
  has_many :notifications, dependent: :destroy

  accepts_nested_attributes_for :authors,
    reject_if: lambda {|a| a[:name].blank?}, allow_destroy: true

  default_scope -> {order created_at: :desc}

  scope :most_books, ->{order(sum_point: :desc).limit(6)}

  scope :reading, ->(user_id) do
    includes(:marks).where(marks: {user_id: user_id, mark_read: 1})
  end

  scope :read, ->(user_id) do
    includes(:marks).where(marks: {user_id: user_id, mark_read: 2})
  end

  scope :favorite, ->(user_id) do
    includes(:marks).where(marks: {user_id: user_id, favorite: true})
  end

  validates :title, presence: true, length: {maximum: 50}
  validates :category, presence: true
  validates :publish_date, presence: true

  mount_uploader :photo, PhotoUploader

  include PublicActivity::Model

  STATUS = ["reading", "read", "favorite"]
end

app/models/supports/book.rb
class Supports::Book
  attr_reader :book

  def initialize book
    @book = book
  end

  Settings.rate.list_rate.each do |rate|
    define_method rate do
      instance_variable_set "@#{rate}", @book.reviews.where(rate:
        Settings.rate.send(rate)).size
    end
  end

  def books
    @books ||= Book.all
  end

  def other_books
    @other_books ||= Book.where(category_id: @book.category_id).limit 6
  end

  def categories
    @categories ||= Category.all
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::AdminController
  load_and_authorize_resource

  def index
    @categories = Category.includes :books
    @q = @books.ransack params[:q]
    @books = @q.result.page(params[:page]).per Settings.per_page
  end

  def show
    @categories = Category.all
  end

  def new
    @category = Category.find_by(id: params[:category_id]) if params[:category_id]
    @book.authors.build
    @authors = Author.all
  end

  def create
    correct_params = correct_book_params
    if correct_params
      @book = Book.new correct_params
      if @book.save
        @authors.each do |author|
          @book.book_authors.create author_id: author
        end
        @categories = Category.all
        @books = Book.all
        @categories = Category.includes :books
        @q = @books.ransack params[:q]
        @books = @q.result.page(params[:page]).per Settings.per_page
      end
    end
  end

  def edit
    @authors = Author.all
  end

  def update
    correct_params = correct_book_params
    if correct_params && @book.update_attributes(correct_params)
      @categories = Category.all
      @books = Book.all
      @categories = Category.includes :books
      @q = @books.ransack params[:q]
      @books = @q.result.page(params[:page]).per Settings.per_page
    end
  end

  def destroy
    @book.destroy
    @categories = Category.includes :books
    @books = Book.all
    @q = @books.ransack params[:q]
    @books = @q.result.page(params[:page]).per Settings.per_page
  end

  private
  def book_params
    params.require(:book).permit :title, :description, :publish_date, :pages,
      :photo, :category_id, authors_attributes: [:id, :name, :_destroy]
  end

  def correct_book_params
    @authors = Array.new
    check_book_params = book_params
    params_book_author = book_params[:authors_attributes]
    params_author = params[:author]
    if params_author
      params_author.each do |id|
        if params[id][:_destroy] == "0" && params_book_author[id][:_destroy] == "0"
          author = Author.find_by name: params_author[id]
          if author
            check_book_params[:authors_attributes][id][:name] = author.name
          else
            check_book_params[:authors_attributes] = check_book_params[:authors_attributes].without id
          end
        elsif params_book_author[id][:_destroy] == "1"
          params_book_author.without id
        end
      end
    end

    params_book_author = check_book_params[:authors_attributes].to_a
    if params_book_author.size != 1
      (0...params_book_author.size).each do |i|
        ((i+1)...params_book_author.size).each do |j|
          if params_book_author[i][1][:name] == params_book_author[j][1][:name]
            @book.errors.add :some_thing, "went wrong"
            return false
          end
        end
      end
    end

    params_book_author = check_book_params[:authors_attributes]
    params_book_author.each do |author|
      if (aut = Author.find_by name: params_book_author[author][:name])
        @authors.push aut.id
        check_book_params[:authors_attributes] = check_book_params[:authors_attributes].without author
      end
    end
    check_book_params
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource
  before_action :load_data, only: :show

  def index
    @books = (params[:type].nil? || params[:type] == "all") ? @books :
      @books.send("#{params[:type]}", current_user.id)
    @q = @books.ransack params[:q]
    @books = @q.result.page(params[:page]).per Settings.per_page
  end

  def show
    @review = Review.new
  end

  private
  def load_data
    @supports = Supports::Book.new @book
    @mark = current_user.marks.find_by book_id: @book.id
    unless @mark
      @mark = current_user.marks.create! book_id: @book.id
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/books/_author_fields.html.erb
<fieldset>
  <a class="nht-other-author" href=""><p class="<%= f.index %>"><%=  t "book.another_author" %></p></a>
  <div class="input-group">
    <span class="input-group-addon">
      <%= f.hidden_field :_destroy, value: 0 %>
      <%= link_to "#", class: "remove_fields" do %>
        <span class='glyphicon glyphicon-minus small'></span>
      <% end %>
      <i class="fa fa-user nht-icon" aria-hidden="true"></i>
    </span>
    <%= f.select :name, @authors.collect {|author|
      [author.name]}, {},
      class: "form-control nht-multi nht-admin-book-author-multi-#{f.index}" %>
    <%= text_field :author, "#{f.index}", placeholder: t("book.author"),
      class: "form-control nht-single nht-admin-book-author-single-#{f.index}",
      list: "authors" %>
    <%= hidden_field "#{f.index}", :_destroy, value: 1 %>
    <datalist id="authors">
      <% @authors.each do |author| %>
        <option value="<%= author.name %>">
      <% end %>
    </datalist>
  </div>
</fieldset>

app/views/admin/books/_book.html.erb
<div class="col-sm-10 col-xs-10 col-md-10 col-lg-10 col-sm-offset-1
  col-xs-offset-1 col-md-offset-1 col-lg-offset-1 nht-admin-book">
  <div class="nht-book-box padding" id="nht-admin-book-content">
    <%= render "book_show" %>
  </div>
</div>

app/views/admin/books/_book_index.html.erb
<table class="table table-bordered table-striped table-hover nht-admin-book-table">
  <thead class="thead-default">
    <tr>
      <th><%= sort_link @q, :photo, t("book.photo") %></th>
      <th><%= sort_link @q, :title, t("book.title") %></th>
      <th><%= sort_link @q, :category, t("book.category") %></th>
      <th><%= sort_link @q, :author_name, t("book.author") %></th>
      <th><%= sort_link @q, :rate, t("book.rate") %></th>
      <th><%= sort_link @q, :pages, t("book.pages") %></th>
      <th><%= sort_link @q, :publish_date, t("book.publish_date") %></th>
      <th><%= sort_link @q, :description, t("book.description") %></th>
      <th><%= sort_link @q, :created_at, t("book.created_at") %></th>
      <th><%= sort_link @q, :updated_at, t("book.updated_at") %></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= image_tag book.photo.url, class: "nht-admin-book-photo" %>
        </td>
        <td>
          <%= link_to book.title, [:admin, book], remote: true %>
        </td>

        <td>
          <%= link_to book.category.name, [:admin, book.category] %>
        </td>

        <td>
          <% book.authors.each do |author| %>
            <%= author.name %>
          <% end %>
        </td>

        <td>
          <%= book.sum_rate == 0 ? 0 : (book.sum_point.to_f / book.sum_rate).round(1) %>
        </td>

        <td>
          <%= book.pages %>
        </td>

        <td>
          <%= l book.publish_date, format: :default %>
        </td>

        <td>
          <%= truncate(book.description, length: Settings.admin_content_length) %>
        </td>

        <td>
          <%= l book.created_at, format: :default %>
        </td>

        <td>
          <%= l book.updated_at, format: :default %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @books, remote: true %>

app/views/admin/books/_book_show.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= link_to "<i class='fa fa-times' aria-hidden='true'></i>".html_safe, "#",
      data: {dismiss: "modal"}, class: "close" %>
    <h2 class="nht-book-address-top">
      <%= @book.title %>
    </h2>
    <hr>

    <div class="nht-admin-book-content">
      <div class="col-sm-12 col-xs-10 col-md-4 col-lg-4 nht-book-content-left">
        <%= image_tag @book.photo.url, class: "nht-book-photo" %>
        <div class="nht-book-detail">
          <p class="author">
            <% @book.authors.each do |author| %>
              <%= author.name %>
            <% end %>
          </p>
          <p class="publish_date"><em><%= l @book.publish_date, format: :default %></em></p>

          <div class="title">
            <p class="nht-book-attribute"><%= t "book.pages" %>:</p>
            <span class="nht-book-attribute-value"> <%= @book.pages %></span>
            <div class="clearfix"></div>
          </div>
        </div>
        <div class="clearfix"></div>
      </div>

      <div class="col-md-8 col-lg-8 nht-book-content-right">
        <div class="nht-book-content-right-detail">
          <div class="nht-book-description">
            <h4 class="nht-book-description-title">
              <%= t "book.description" %>
            </h4>
            <div class="nht-book-description-content">
              <%= @book.description %>
            </div>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
    <%= link_to t("book.delete"), admin_book_path(@book), method: :delete, data: {
      confirm: t("book.confirm")}, remote: true, class: "btn btn-danger nht-admin-btn-book" %>
    <%= link_to t("book.edit"), edit_admin_book_path(@book), remote: true,
      class: "btn btn-primary nht-admin-btn-book" %>
    <div class="clearfix"></div>
  </div>
</div>

app/views/admin/books/_form.html.erb
<% provide :title, title %>
<% provide :btn_title, btn_title %>

<div class="col-sm-10 col-xs-10 col-md-10 col-lg-10 col-sm-offset-1
  col-xs-offset-1 col-md-offset-1 col-lg-offset-1 nht-admin-book-form">
  <div class="modal-dialog">
    <div class="modal-content">
      <h1><%= title %></h1>
      <%= form_for [:admin, @book], authenticity_token: true, remote: true do |f| %>
        <div id="nht-book-errors"></div>
        <div class="input-group">
          <span class="input-group-addon">
            <i class="glyphicon glyphicon-th-list nht-icon" aria-hidden="true"></i>
          </span>
          <% if @category %>
            <%= text_field :category, :id, value: @category.name,
              disabled: true, class: "form-control" %>
            <%= f.hidden_field :category_id, value: @category.id %>
          <% else %>
            <%=  f.select :category_id, @categories.collect {|category|
              [category.name, category.id]}, {}, class: "form-control" %>
          <% end %>
        </div>

        <div>
          <%= f.fields_for :authors do |author| %>
            <%= render "author_fields", f: author %>
            <%= link_to_add_fields f, :authors %>
          <% end %>
        </div>

        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-info nht-icon" aria-hidden="true"></i>
          </span>
          <%= f.text_field :title, placeholder: t("book.title"),
            class: "form-control" %>
        </div>

        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-file nht-icon" aria-hidden="true"></i>
          </span>
          <%= f.number_field :pages, class: "form-control" %>
        </div>

        <div class="input-group">
          <span class="input-group-addon">
            <span class="fa fa-calendar nht-icon"></span>
          </span>
          <%= f.text_field :publish_date, class: "form-control",
            placeholder: t("book.publish_date"),
            data: {provide: "datepicker"}, "data-date-format" => "dd/mm/yyyy" %>
        </div>

        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-file-image-o nht-icon" aria-hidden="true"></i>
          </span>
          <%= f.file_field :photo, class: "form-control" %>
        </div>

        <div>
          <%= f.label :description, t("book.description") %>
          <%= f.text_area :description, placeholder: t("book.description"),
            class: "form-control nht-book-description" %>
        </div>

        <%= f.submit btn_title, class: "btn btn-primary nht-admin-btn-book" %>
        <%= link_to t("book.cancel"), "#", data: {dismiss: "modal"},
          class: "btn btn-danger nht-admin-btn-book" %>
        <div class="clearfix"></div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/books/create.js.erb
<% if @book.errors.full_messages.present? %>
  $('#nht-book-errors').html('<%= j render "shared/error_messages", object: @book %>')
<% else %>
  $('#nht-admin-book-index').html('<%= j render "book_index" %>')
  $('#admin-book-form').modal('hide');
<% end %>

app/views/admin/books/destroy.js.erb
$('#nht-admin-book-index').html('<%= j render "book_index" %>')
$('#admin-book-form').modal('hide');

app/views/admin/books/edit.js.erb
$('#nht-admin-book-content').html('<%= j render "form", title: "Edit book", btn_title: "Save" %>');

app/views/admin/books/index.html.erb
<div class="nht-admin-book-index">
  <h1><%= t "book.all_book" %></h1>
  <div class="col-xs-6 col-sm-6 col-md-12 col-lg-12">
      <div class="nht-admin-search-form">
        <%= search_form_for [:admin, @q], remote: true do |f| %>
          <div class="col-sm-8 col-xs-8 col-md-6 col-md-ofset-2 col-lg-6 col-lg-offset-2">
            <div class="input-group">
              <span class="input-group-addon">
                <i class="fa fa-info nht-icon" aria-hidden="true"></i>
              </span>
              <%= f.text_field :title_cont, placeholder: t("book.title"),
                class: "form-control" %>
            </div>
          </div>
          <div class="nht-btn-search col-md-4 col-lg-4">
            <%= f.submit t(:search), class: "btn btn-primary" %>
            <%= link_to t("book.new"), new_admin_book_path, remote: true,
              class: "btn btn-primary" %>
            <div class="clearfix"></div>
          </div>
        <% end %>
      </div>
    </div>
    <div id="nht-admin-book-index">
      <%= render "book_index" %>
    </div>
  </div>
</div>
<div id="admin-book-form" class="modal fade"></div>

app/views/admin/books/index.js.erb
$('#nht-admin-book-index').html('<%= j render "book_index" %>')

app/views/admin/books/new.js.erb
$('#admin-book-form').html('<%= j render "form", btn_title: "Create", title: "New book" %>');
$('#admin-book-form').modal('show');

app/views/admin/books/show.js.erb
$('#admin-book-form').html('<%= j render "book" %>');
$('#admin-book-form').modal('show');

app/views/admin/books/update.js.erb
<% if @book.errors.full_messages.present? %>
  $('#nht-book-errors').html('<%= j render "shared/error_messages", object: @book %>')
<% else %>
  $('#nht-admin-book-index').html('<%= j render "book_index" %>')
  $('#admin-book-form').modal('hide');
<% end %>