config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  mount ActionCable.server => "/cable"

  devise_for :users, controllers: {
    registrations: "registrations",
    omniauth_callbacks: "omniauth_callbacks"
  }
  root "pages#index"
  get "/pages/:page", to: "pages#show"

  resources :users do
    resources :list_books, only: :index
    resources :requests, except: [:show, :edit, :update]
  end
  resources :follows, only: [:create, :destroy]
  resources :activities
  resources :categories, only: [:show, :index]
  resources :books, only: [:show, :index] do
    resources :reviews
  end
  resources :reviews, only: :show do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:new, :create, :destroy, :edit, :update]
  end
  resources :marks, only: :update
  resources :favorite_authors, only: [:create, :destroy]
  resources :feed_backs, only: [:new, :create]
  resources :authors, only: [:index, :show]

  namespace :admin do
    root to: "books#index", as: :root
    resources :categories
    resources :books
    resources :users, only: [:index, :show, :destroy]
    resources :requests, only: [:index, :update]
  end
end

app/views/layouts/admin/_header.html.erb
<header class="main-header">
  <div class="logo">
    <div>
      <%= link_to t("admin.home.title"), admin_root_path %>
    </div>
  </div>

  <nav class="navbar navbar-static-top" role="navigation">
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button"></a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag current_user.image.url, class: "user-image" %>
            <span class="hidden-xs"><%= current_user.name %></span>
            <ul class="dropdown-menu dn-dropdown-menu">
              <li>
                <%= link_to t("sessions.sign_out"),
                  destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </a>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/admin/_sidebar.html.erb
<aside class="main-sidebar">
  <section class="sidebar">
    <ul class="sidebar-menu">
      <li class="nht-book active">
        <%= link_to admin_books_path do %>
          <i class="fa fa-book nht-icon"></i>
          <%= t "book.all_book" %>
        <% end %>
      </li>

      <li class="nht-category">
        <%= link_to admin_categories_path do %>
          <i class="glyphicon glyphicon-th-list nht-icon"></i>
          <%= t "category.all_category" %>
        <% end %>
      </li>

      <li class="nht-user">
        <%= link_to admin_users_path do %>
          <i class="fa fa-user nht-icon"></i>
          <%= t "user.all_user" %>
        <% end %>
      </li>

      <li class="nht-request">
        <%= link_to admin_requests_path do %>
          <i class="fa fa-question-circle nht-icon"></i>
          <%= t "request.all" %>
        <% end %>
      </li>
    </ul>
  </section>
</aside>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t :title %></title>
    <%= stylesheet_link_tag "admin/application", media: "all",
      "data-turbolinks-track": true %>
    <%= javascript_include_tag "admin/application",
      "data-turbolinks-track": true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <%= render "layouts/admin/header" %>
      <%= render "layouts/admin/sidebar" %>
      <div class="content-wrapper dn-content">
        <div id="flash">
          <% flash.each do |message_type, message| %>
            <% if  message_type == "notice" %>
              <% message_type = "success" %>
            <% end %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
        </div>
        <section class="content">
          <%= yield %>
        </section>
        <div class="clearfix"></div>
      </div>
      <div class="control-sidebar-bg"></div>
    </div>
  </body>
</html>