config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  mount ActionCable.server => "/cable"

  devise_for :users, controllers: {
    registrations: "registrations",
    omniauth_callbacks: "omniauth_callbacks"
  }
  root "pages#index"
  get "/pages/:page", to: "pages#show"

  resources :users do
    resources :list_books, only: :index
    resources :requests, except: [:show, :edit, :update]
  end
  resources :follows, only: [:create, :destroy]
  resources :activities
  resources :categories, only: [:show, :index]
  resources :books, only: [:show, :index] do
    resources :reviews
  end
  resources :reviews, only: :show do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:new, :create, :destroy, :edit, :update]
  end
  resources :marks, only: :update
  resources :favorite_authors, only: [:create, :destroy]
  resources :feed_backs, only: [:new, :create]
  resources :authors, only: [:index, :show]

  namespace :admin do
    root to: "books#index", as: :root
    resources :categories
    resources :books
    resources :users, only: [:index, :show, :destroy]
    resources :requests, only: [:index, :update]
  end
end

app/views/shared/_book_index.html.erb
<% @books.each do |book| %>
  <div class="col-sm-6 col-sm-4 col-md-3 col-log-3 nht-list-book-content">
    <%= link_to book do %>
      <%= image_tag book.photo.url, class: "nht-book-photo", alt: book.title %>
    <% end %>
    <p class="nht-book-author"><%= book.author %></p>
    <hr>
  </div>
<% end %>
<%= paginate @books, remote: true %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li class="nht-fix-alert alert alert-danger"><%= msg %></li>
      <% end %>
      <div class="clearfix"></div>
    </ul>
  </div>
<% end %>

app/views/shared/_like.html.erb
<%= link_to review_likes_path(review), method: :post, remote: true,
  class: "w3-btn w3-theme-d1 w3-margin-bottom" do %>
  <i class="fa fa-thumbs-up"></i>
  <%= t "review.like" %>
<% end %>

app/views/shared/_like_form.html.erb
<div id="nht-like-<%= review.id %>" class="nht-like">
  <% if current_user.like? review %>
    <%= render "shared/unlike", review: review,
      like: current_user.likes.find_by(review_id: review.id) %>
  <% else %>
    <%= render "shared/like", review: review %>
  <% end %>
</div>

app/views/shared/_sum_like_cmt.html.erb
<i class="fa fa-thumbs-up"> <%= review.sum_likes %></i>
<i class="fa fa-comment"> <%= review.sum_comments %></i>

app/views/shared/_unlike.html.erb
<%= link_to review_like_path(review, like), method: :delete, remote: true,
  class: "w3-btn w3-theme-d1 w3-margin-bottom" do %>
  <i class="fa fa-thumbs-down"></i>
  <%= t "review.unlike" %>
<% end %>