config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  mount ActionCable.server => "/cable"

  devise_for :users, controllers: {
    registrations: "registrations",
    omniauth_callbacks: "omniauth_callbacks"
  }
  root "pages#index"
  get "/pages/:page", to: "pages#show"

  resources :users do
    resources :list_books, only: :index
    resources :requests, except: [:show, :edit, :update]
  end
  resources :follows, only: [:create, :destroy]
  resources :activities
  resources :categories, only: [:show, :index]
  resources :books, only: [:show, :index] do
    resources :reviews
  end
  resources :reviews, only: :show do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:new, :create, :destroy, :edit, :update]
  end
  resources :marks, only: :update
  resources :favorite_authors, only: [:create, :destroy]
  resources :feed_backs, only: [:new, :create]
  resources :authors, only: [:index, :show]

  namespace :admin do
    root to: "books#index", as: :root
    resources :categories
    resources :books
    resources :users, only: [:index, :show, :destroy]
    resources :requests, only: [:index, :update]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy

  default_scope -> {order created_at: :desc}

  validates :name, presence: true

  def sum_book
    books.size
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  load_and_authorize_resource

  def new
  end

  def create
    if @category.save
      @categories = @categories.includes :books
      @q = @categories.ransack params[:q]
      @categories = @q.result.page(params[:page]).per Settings.per_page
    end
  end

  def index
    @categories = @categories.includes :books
    @q = @categories.ransack params[:q]
    @categories = @q.result.page(params[:page]).per Settings.per_page
  end

  def show
    @q = @category.books.ransack params[:q]
    @books = @q.result.page(params[:page]).per Settings.per_page
  end

  def new
  end

  def create
    if @category.save
      @categories = @categories.includes :books
      @q = @categories.ransack params[:q]
      @categories = @q.result.page(params[:page]).per Settings.per_page
    end
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      @categories = @categories.includes :books
      @q = @categories.ransack params[:q]
      @categories = @q.result.page(params[:page]).per Settings.per_page
    end
  end

  def destroy
    @category.destroy
    flash[:success] = t "category.success"
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit :name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource

  def show
    @q = @category.books.ransack params[:q]
    @books = @q.result.page(params[:page]).per Settings.per_page
  end
end

app/views/admin/categories/_book_index.html.erb
<table class="table table-bordered table-striped table-hover nht-admin-book-table">
  <thead class="thead-default">
    <tr>
      <th><%= sort_link @q, :photo, t("book.photo") %></th>
      <th><%= sort_link @q, :title, t("book.title") %></th>
      <th><%= sort_link @q, :author_name, t("book.author") %></th>
      <th><%= sort_link @q, :rate, t("book.rate") %></th>
      <th><%= sort_link @q, :pages, t("book.pages") %></th>
      <th><%= sort_link @q, :publish_date, t("book.publish_date") %></th>
      <th><%= sort_link @q, :description, t("book.description") %></th>
      <th><%= sort_link @q, :created_at, t("book.created_at") %></th>
      <th><%= sort_link @q, :updated_at, t("book.updated_at") %></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= image_tag book.photo.url, class: "nht-admin-book-photo" %>
        </td>
        <td>
          <%= link_to book.title, [:admin, book], remote: true %>
        </td>

        <td>
          <% book.authors.each do |author| %>
            <%= author.name %>
          <% end %>
        </td>

        <td>
          <%= book.sum_rate == 0 ? 0 : (book.sum_point / book.sum_rate) %>
        </td>

        <td>
          <%= book.pages %>
        </td>

        <td>
          <%= l book.publish_date, format: :default %>
        </td>

        <td>
          <%= truncate(book.description, length: Settings.admin_content_length) %>
        </td>

        <td>
          <%= l book.created_at, format: :default %>
        </td>

        <td>
          <%= l book.updated_at, format: :default %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @books, remote: true %>

app/views/admin/categories/_category_index.html.erb
<table class="table table-bordered table-striped table-hover">
  <thead class="thead-default">
    <tr>
      <th><%= sort_link @q, :name, t("category.name") %></th>
      <th><%= sort_link @q, :sum_book, t("category.sum_book") %></th>
      <th><%= sort_link @q, :created_at, t("category.created_at") %></th>
      <th><%= sort_link @q, :updated_at, t("category.updated_at") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td>
          <%= link_to category.name, [:admin, category] %>
        </td>

        <td>
          <%= category.sum_book %>
        </td>

        <td>
          <%= l category.created_at, format: :default %>
        </td>

        <td>
          <%= l category.updated_at, format: :default %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @categories, remote: true %>

app/views/admin/categories/_form.html.erb
<% provide :title, title %>
<% provide :btn_title, btn_title %>
<div class="col-sm-10 col-xs-10 col-md-10 col-lg-10 col-sm-offset-1
  col-xs-offset-1 col-md-offset-1 col-lg-offset-1 nht-admin-category">
  <div class="modal-dialog">
    <div class="modal-content">
      <h1><%= title %></h1>
      <%= form_for [:admin, @category], remote: true do |f| %>
        <div id="nht-category-errors"></div>
        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-info nht-icon" aria-hidden="true"></i>
          </span>
          <%= f.text_field :name, placeholder: t("category.name"),
            class: "form-control" %>
        </div>

        <%= f.submit btn_title, class: "btn btn-primary nht-admin-btn-category" %>
        <%= link_to t("category.cancel"), "#", data: {dismiss: "modal"},
          class: "btn btn-danger nht-admin-btn-category" %>
        <div class="clearfix"></div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/create.js.erb
<% if @category.errors.full_messages.present? %>
  $('#nht-category-errors').html('<%= j render "shared/error_messages", object: @category %>')
<% else %>
  $('#nht-admin-category-index').html('<%= j render "category_index" %>')
  $('#admin-category-form').modal('hide');
<% end %>

app/views/admin/categories/edit.js.erb
$('#admin-category-form').html('<%= j render "form", btn_title: "Save", title: "Edit category" %>');
$('#admin-category-form').modal('show')

app/views/admin/categories/index.html.erb
<div class="nht-admin-category-index">
  <h1><%= t "category.all_category" %></h1>
  <div class="col-xs-6 col-sm-6 col-md-12 col-lg-12">
    <div class="nht-admin-search-form">
      <%= search_form_for [:admin, @q], remote: true do |f| %>
        <div class="col-sm-8 col-xs-8 col-md-6 col-md-ofset-2 col-lg-6 col-lg-offset-2">
          <div class="input-group">
            <span class="input-group-addon">
              <i class="fa fa-info nht-icon" aria-hidden="true"></i>
            </span>
            <%= f.text_field :name_cont, placeholder: t("category.name"),
              class: "form-control" %>
          </div>
        </div>
        <div class="nht-btn-search col-md-4 col-lg-4">
          <%= f.submit t(:search), class: "btn btn-primary" %>
          <%= link_to t("category.new"), new_admin_category_path, remote: true,
          class: "btn btn-primary" %>
          <div class="clearfix"></div>
        </div>
      <% end %>
    </div>
    <div id="nht-admin-category-index">
      <%= render "category_index" %>
    </div>
  </div>
</div>
<div id="admin-category-form" class="modal fade"></div>

app/views/admin/categories/index.js.erb
$('#nht-admin-category-index').html('<%= j render "category_index" %>')

app/views/admin/categories/new.js.erb
$('#admin-category-form').html('<%= j render "form", btn_title: "Create", title: "New category" %>');
$('#admin-category-form').modal('show')

app/views/admin/categories/show.html.erb
<div class="nht-admin-book-index">
  <h1><%= t "category.all_book", category: @category.name %></h1>
  <div class="col-xs-6 col-sm-6 col-md-12 col-lg-12">
    <div class="nht-admin-search-form">
      <%= search_form_for [:admin, @q], remote: true do |f| %>
        <div class="col-sm-8 col-xs-8 col-md-6 col-md-ofset-2 col-lg-6 col-lg-offset-2">
          <div class="input-group">
            <span class="input-group-addon">
              <i class="fa fa-info nht-icon" aria-hidden="true"></i>
            </span>
            <%= f.text_field :title_cont, placeholder: t("book.title"),
              class: "form-control" %>
          </div>
        </div>
        <div class="nht-btn-search col-md-4 col-lg-4">
          <%= f.submit t(:search), class: "btn btn-primary" %>
          <%= link_to t("book.new"), new_admin_book_path(category_id: @category),
            remote: true, class: "btn btn-primary" %>
          <div class="clearfix"></div>
        </div>
      <% end %>
    </div>
    <div id="nht-admin-book-index">
      <%= render "book_index" %>
    </div>
    <%= link_to t("category.delete"), admin_category_path(@category), method: :delete,
      data: {confirm: t("category.confirm")}, class: "btn btn-danger nht-admin-btn-category" %>
    <%= link_to t("category.edit"), edit_admin_category_path(@category), remote: true,
      class: "btn btn-primary nht-admin-btn-category" %>
    <div class="clearfix"></div>
  </div>
  <div class="clearfix"></div>
</div>
<div id="admin-category-form" class="modal fade"></div>
<div id="admin-book-form" class="modal fade"></div>

app/views/admin/categories/update.js.erb
<% if @category.errors.full_messages.present? %>
  $('#nht-category-errors').html('<%= j render "shared/error_messages", object: @category %>')
<% else %>
  $('#nht-admin-category-index').html('<%= j render "category_index" %>')
  $('#admin-category-form').modal('hide');
<% end %>